/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 5
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 12
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_directive = 1,
  sym_control_word = 2,
  sym_component = 3,
  sym_interpolation = 4,
  sym_html_tag = 5,
  sym_comment = 6,
  sym_string = 7,
  sym_punctuation = 8,
  sym_text = 9,
  sym_source_file = 10,
  aux_sym_source_file_repeat1 = 11,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_directive] = "directive",
  [sym_control_word] = "control_word",
  [sym_component] = "component",
  [sym_interpolation] = "interpolation",
  [sym_html_tag] = "html_tag",
  [sym_comment] = "comment",
  [sym_string] = "string",
  [sym_punctuation] = "punctuation",
  [sym_text] = "text",
  [sym_source_file] = "source_file",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_directive] = sym_directive,
  [sym_control_word] = sym_control_word,
  [sym_component] = sym_component,
  [sym_interpolation] = sym_interpolation,
  [sym_html_tag] = sym_html_tag,
  [sym_comment] = sym_comment,
  [sym_string] = sym_string,
  [sym_punctuation] = sym_punctuation,
  [sym_text] = sym_text,
  [sym_source_file] = sym_source_file,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_control_word] = {
    .visible = true,
    .named = true,
  },
  [sym_component] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym_html_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
};

static const TSCharacterRange sym_text_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '&'}, {'(', ';'}, {'=', '?'}, {'A', 'z'}, {'|', '|'},
  {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(57);
      ADVANCE_MAP(
        '\n', 77,
        '"', 71,
        '\'', 72,
        '<', 70,
        '@', 73,
        'e', 75,
        '{', 69,
        '}', 67,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ':' ||
          lookahead == '[' ||
          lookahead == ']') ADVANCE(68);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(66);
      if (lookahead == '\\') ADVANCE(55);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(66);
      if (lookahead == '\\') ADVANCE(56);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '>') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(3);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(51);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(52);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(50);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(49);
      if (lookahead == 'y') ADVANCE(30);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(45);
      if (lookahead == 'l') ADVANCE(40);
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 21:
      if (lookahead == 'f') ADVANCE(58);
      if (lookahead == 'm') ADVANCE(13);
      END_STATE();
    case 22:
      if (lookahead == 'f') ADVANCE(59);
      END_STATE();
    case 23:
      if (lookahead == 'g') ADVANCE(33);
      END_STATE();
    case 24:
      if (lookahead == 'g') ADVANCE(17);
      END_STATE();
    case 25:
      if (lookahead == 'g') ADVANCE(14);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(43);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(42);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 31:
      if (lookahead == 'm') ADVANCE(32);
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 32:
      if (lookahead == 'm') ADVANCE(19);
      if (lookahead == 'p') ADVANCE(41);
      END_STATE();
    case 33:
      if (lookahead == 'm') ADVANCE(20);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(58);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(46);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 38:
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 39:
      if (lookahead == 'o') ADVANCE(44);
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 40:
      if (lookahead == 'o') ADVANCE(46);
      END_STATE();
    case 41:
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 42:
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 43:
      if (lookahead == 'p') ADVANCE(46);
      END_STATE();
    case 44:
      if (lookahead == 'r') ADVANCE(58);
      END_STATE();
    case 45:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 46:
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 47:
      if (lookahead == 't') ADVANCE(65);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 49:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 51:
      if (lookahead == 'v') ADVANCE(28);
      END_STATE();
    case 52:
      if (lookahead == 'w') ADVANCE(58);
      END_STATE();
    case 53:
      if (lookahead == '}') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '{') ADVANCE(53);
      END_STATE();
    case 54:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 55:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 56:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_directive);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_control_word);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_control_word);
      if (lookahead == ' ') ADVANCE(27);
      if ((!eof && set_contains(sym_text_character_set_1, 9, lookahead))) ADVANCE(78);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_component);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_interpolation);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_html_tag);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_punctuation);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_punctuation);
      if ((!eof && set_contains(sym_text_character_set_1, 9, lookahead))) ADVANCE(78);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_punctuation);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(53);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '!') ADVANCE(6);
      if (lookahead == '/') ADVANCE(54);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '"') ADVANCE(66);
      if (lookahead == '\\') ADVANCE(55);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\'') ADVANCE(66);
      if (lookahead == '\\') ADVANCE(56);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'c') ADVANCE(38);
      if (lookahead == 'f') ADVANCE(39);
      if (lookahead == 'i') ADVANCE(21);
      if (lookahead == 'l') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(10);
      if (lookahead == 'r') ADVANCE(11);
      if (lookahead == 's') ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(61);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(60);
      if ((!eof && set_contains(sym_text_character_set_1, 9, lookahead))) ADVANCE(78);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'l') ADVANCE(76);
      if ((!eof && set_contains(sym_text_character_set_1, 9, lookahead))) ADVANCE(78);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 's') ADVANCE(74);
      if ((!eof && set_contains(sym_text_character_set_1, 9, lookahead))) ADVANCE(78);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_text);
      if ((!eof && set_contains(sym_text_character_set_1, 9, lookahead))) ADVANCE(78);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_directive] = ACTIONS(1),
    [sym_control_word] = ACTIONS(1),
    [sym_component] = ACTIONS(1),
    [sym_interpolation] = ACTIONS(1),
    [sym_html_tag] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_punctuation] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_directive] = ACTIONS(5),
    [sym_control_word] = ACTIONS(7),
    [sym_component] = ACTIONS(5),
    [sym_interpolation] = ACTIONS(5),
    [sym_html_tag] = ACTIONS(5),
    [sym_comment] = ACTIONS(5),
    [sym_string] = ACTIONS(5),
    [sym_punctuation] = ACTIONS(7),
    [sym_text] = ACTIONS(7),
  },
  [STATE(2)] = {
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(9),
    [sym_directive] = ACTIONS(11),
    [sym_control_word] = ACTIONS(13),
    [sym_component] = ACTIONS(11),
    [sym_interpolation] = ACTIONS(11),
    [sym_html_tag] = ACTIONS(11),
    [sym_comment] = ACTIONS(11),
    [sym_string] = ACTIONS(11),
    [sym_punctuation] = ACTIONS(13),
    [sym_text] = ACTIONS(13),
  },
  [STATE(3)] = {
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_directive] = ACTIONS(17),
    [sym_control_word] = ACTIONS(20),
    [sym_component] = ACTIONS(17),
    [sym_interpolation] = ACTIONS(17),
    [sym_html_tag] = ACTIONS(17),
    [sym_comment] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [sym_punctuation] = ACTIONS(20),
    [sym_text] = ACTIONS(20),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [23] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_plume(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "plume",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
