//
//  PlumeSwiftGenerator.swift
//  Plume — compiling back-end
//
//  Lowers parsed Plume components to Embedded-Swift-clean `render` functions that
//  write HTML bytes into a `PlumeRuntime.HTML` buffer. Each typed `@component`
//  becomes one free function:
//
//      @component PostPage(post: Post, related: [Post] = [], currentUser: User?)
//          ->  func postPage(post: Post, related: [Post] = [], currentUser: User?,
//                            into out: inout HTML)
//
//  Generated code is pure and synchronous: no `await`, no I/O, no concurrency.
//

import Foundation

/// Options controlling Swift code generation.
public struct PlumeSwiftOptions: Sendable {
    /// The runtime module the generated code imports (`import PlumeRuntime`).
    public var runtimeModuleName: String
    /// Emit `#sourceLocation` directives so `swiftc` errors point at the `.plume`
    /// source line rather than at generated Swift.
    public var emitSourceLocations: Bool
    /// The path embedded in `#sourceLocation(file:)`. Defaults to each node's
    /// source name when `nil`.
    public var sourcePath: String?

    public init(
        runtimeModuleName: String = "PlumeRuntime",
        emitSourceLocations: Bool = true,
        sourcePath: String? = nil
    ) {
        self.runtimeModuleName = runtimeModuleName
        self.emitSourceLocations = emitSourceLocations
        self.sourcePath = sourcePath
    }
}

struct PlumeSwiftGenerator {
    let components: [String: PlumeComponent]
    let options: PlumeSwiftOptions

    private var output = ""
    private var indentationLevel = 0
    private var uniqueCounter = 0
    /// Scope attribute names applied to opening tags in the component currently
    /// being lowered (one per scoped `@style` it declares). Empty when none.
    private var activeScopeAttributes: [String] = []

    init(components: [String: PlumeComponent], options: PlumeSwiftOptions) {
        self.components = components
        self.options = options
    }

    // MARK: - Entry

    /// Generates a complete Swift source file for every `@component` defined in
    /// `topLevel`, in source order.
    mutating func generate(topLevel nodes: [PlumeNode]) throws -> String {
        let definitions = componentDefinitions(in: nodes)
        try rejectTopLevelContent(in: nodes)
        emitHeader()
        for component in definitions {
            try lowerComponent(component)
        }
        return output
    }

    private func componentDefinitions(in nodes: [PlumeNode]) -> [PlumeComponent] {
        nodes.compactMap { node in
            if case .componentDefinition(let component) = node { return component }
            return nil
        }
    }

    /// The unit of compilation is the component. Stray renderable content at the
    /// top level (output, control flow, component calls) has no typed signature to
    /// lower into, so it is rejected with a clear, source-located message.
    private func rejectTopLevelContent(in nodes: [PlumeNode]) throws {
        for node in nodes {
            switch node {
            case .componentDefinition, .text:
                continue
            case .output(_, let context),
                .loop(_, _, _, let context),
                .conditional(_, _, _, let context),
                .componentCall(_, _, _, let context),
                .slot(_, _, let context),
                .assign(_, _, let context),
                .state(_, _, let context):
                throw PlumeError.template(
                    "The compiling back-end lowers components: wrap top-level content in an @component before compiling.",
                    context: context)
            default:
                continue
            }
        }
    }

    // MARK: - Header

    private mutating func emitHeader() {
        line("// Generated by Plume \(PlumeVersion.current). Do not edit.")
        line("import \(options.runtimeModuleName)")
        line("")
    }

    // MARK: - Components

    private mutating func lowerComponent(_ component: PlumeComponent) throws {
        let signature = try componentSignature(component)
        line(signature + " {")
        indentationLevel += 1

        // A scoped @style marks the component's elements with a scope attribute;
        // the CSS itself is compiled into the build-time bundle, not emitted here.
        let previousScopes = activeScopeAttributes
        activeScopeAttributes = scopeAttributes(in: component.body)
        defer { activeScopeAttributes = previousScopes }

        // @state lowers to a single serialized initial-state hook the client
        // runtime reads; the values are computed from props at render time.
        try emitStateHook(for: component.body)

        try lowerNodes(component.body)
        indentationLevel -= 1
        line("}")
        line("")

        // A convenience overload that returns a fresh `HTML`, so a handler can render a
        // page in one line: `return .view(postsPage(posts: posts))`. The `into:` form
        // above stays the fast path for composing components into a shared buffer.
        try emitReturningOverload(component)
    }

    private mutating func emitReturningOverload(_ component: PlumeComponent) throws {
        var parameters: [String] = []
        var forwarded: [String] = []
        for parameter in component.parameters {
            let type = parameter.typeAnnotation ?? ""
            var rendered = "\(parameter.name): \(type)"
            if let defaultExpression = parameter.defaultExpression {
                let lowerer = PlumeSwiftExpression(context: component.context)
                rendered += " = \(try lowerer.lower(defaultExpression))"
            }
            parameters.append(rendered)
            forwarded.append("\(parameter.name): \(parameter.name)")
        }
        for slot in slotParameters(of: component) {
            parameters.append("\(slot.swiftName): ((inout HTML) -> Void)? = nil")
            forwarded.append("\(slot.swiftName): \(slot.swiftName)")
        }
        let name = functionName(component.name)
        let call = forwarded.isEmpty ? "\(name)(into: &out)" : "\(name)(\(forwarded.joined(separator: ", ")), into: &out)"
        line("func \(name)(\(parameters.joined(separator: ", "))) -> HTML {")
        indentationLevel += 1
        line("var out = HTML()")
        line(call)
        line("return out")
        indentationLevel -= 1
        line("}")
        line("")
    }

    func componentSignature(_ component: PlumeComponent) throws -> String {
        var parameters: [String] = []
        for parameter in component.parameters {
            guard let type = parameter.typeAnnotation, !type.isEmpty else {
                throw PlumeError.template(
                    "Component \(component.name) parameter `\(parameter.name)` needs a Swift type to be compiled, e.g. `\(parameter.name): String`.",
                    context: component.context)
            }
            var rendered = "\(parameter.name): \(type)"
            if let defaultExpression = parameter.defaultExpression {
                let lowerer = PlumeSwiftExpression(context: component.context)
                rendered += " = \(try lowerer.lower(defaultExpression))"
            }
            parameters.append(rendered)
        }
        // Slots become optional render-closure parameters; `nil` means the caller
        // did not fill the slot, so its fallback content renders instead.
        for slot in slotParameters(of: component) {
            parameters.append("\(slot.swiftName): ((inout HTML) -> Void)? = nil")
        }
        parameters.append("into out: inout HTML")
        return "func \(functionName(component.name))(\(parameters.joined(separator: ", ")))"
    }

    func functionName(_ componentName: String) -> String {
        guard let first = componentName.first else { return componentName }
        return first.lowercased() + componentName.dropFirst()
    }

    // MARK: - Node lowering

    mutating func lowerNodes(_ nodes: [PlumeNode]) throws {
        for node in nodes {
            try lowerNode(node)
        }
    }

    mutating func lowerNode(_ node: PlumeNode) throws {
        switch node {
        case .text(let text):
            lowerText(text)
        case .output(let expression, let context):
            try lowerOutput(expression, context: context)
        case .conditional(let condition, let body, let alternate, let context):
            try lowerConditional(
                condition: condition, body: body, alternate: alternate, context: context)
        case .loop(let variable, let collection, let body, let context):
            try lowerLoop(variable: variable, collection: collection, body: body, context: context)
        case .assign(let name, let expression, let context):
            try lowerAssign(name: name, expression: expression, context: context)
        case .componentCall(let name, let arguments, let body, let context):
            try lowerComponentCall(name: name, arguments: arguments, body: body, context: context)
        case .slot(let name, let fallback, let context):
            try lowerSlot(name: name, fallback: fallback, context: context)
        case .content(_, _, let context):
            throw PlumeError.template(
                "@content can only be used directly inside a component call.", context: context)
        case .componentDefinition:
            // Nested component definitions are lowered at the top level.
            return
        case .state:
            // Collected and emitted once as the state hook in lowerComponent.
            return
        case .style:
            // The CSS compiles into the build-time bundle; the HTML-side hooks are
            // the scope attribute on this component's tags and a RECORDED stylesheet
            // requirement — the response boundary (`Response.view`) splices one
            // `<link>` into the document's `<head>`, wherever the first `@style`
            // appeared. `asset("app.css")` is baked to the content-hashed URL by the
            // build's asset pass. Fragments (no `<head>`) are left untouched.
            line("out.requireStylesheet(asset(\"app.css\"))")
        case .script:
            // The script's code compiles into the build-time bundle; here we record
            // that this response needs it (spliced into <head> at the boundary).
            line("out.requireScript(asset(\"app.js\"))")
        case .navigation(let declaration):
            emitNavigationMarker(declaration.resource)
        case .image(let declaration):
            throw outOfSubset(
                "@image (the responsive-image asset pipeline is a build-time concern)",
                context: declaration.context)
        }
    }

    // MARK: - Text & output

    mutating func lowerText(_ text: String) {
        guard !text.isEmpty else { return }
        let emitted = activeScopeAttributes.isEmpty
            ? text : Self.applyScopeAttributes(to: text, attributes: activeScopeAttributes)
        line("out.literal(\(swiftStringLiteral(emitted)))")
    }

    mutating func lowerOutput(_ expression: String, context: PlumeSourceContext?) throws {
        locatedLine(try outputCall(expression, context: context), context: context)
    }

    /// Computes the `out.text(...)` / `out.raw(...)` call for an output expression
    /// without emitting it. Shared with the renderable-subset checker so both use
    /// exactly the same definition of the supported subset.
    func outputCall(_ expression: String, context: PlumeSourceContext?) throws -> String {
        let segments = PlumeSwiftScanning.splitTopLevel(
            expression, separator: "|", skippingLogicalPipes: true)
        let lowerer = PlumeSwiftExpression(context: context)
        guard let first = segments.first else {
            return "out.text(\"\")"
        }
        var value = try lowerer.lower(first)
        var raw = false
        for segment in segments.dropFirst() {
            let filter = parseFilter(segment)
            switch filter.name {
            case "raw":
                raw = true
            case "escape":
                // Transform to the escaped string (not just toggle the default), so a
                // following `raw` emits the entities rather than the source — matching
                // the interpreter's `escape`.
                value = "Plume.escaped(\(value))"
                raw = true
            default:
                value = try applyValueFilter(
                    filter.name, arguments: filter.arguments, to: value,
                    lowerer: lowerer, context: context)
            }
        }
        return raw ? "out.raw(\(value))" : "out.text(\(value))"
    }

    /// Applies one Embedded-safe value filter to an already-lowered value. Numeric
    /// filters lower to plain Swift arithmetic; `default` uses a runtime helper.
    /// Foundation/Unicode-backed filters (case, regex, date, json, slug, …) are
    /// build-time-only and rejected with a clear message.
    func applyValueFilter(
        _ name: String, arguments: [String], to value: String,
        lowerer: PlumeSwiftExpression, context: PlumeSourceContext?
    ) throws -> String {
        let lowered = try arguments.map { try lowerer.lower($0) }
        func argument(_ index: Int) throws -> String {
            guard index < lowered.count else {
                throw PlumeError.template(
                    "The filter `\(name)` needs an argument.", context: context)
            }
            return lowered[index]
        }
        switch name {
        case "plus": return "(\(value) + \(try argument(0)))"
        case "minus": return "(\(value) - \(try argument(0)))"
        case "times": return "(\(value) * \(try argument(0)))"
        // Double math + zero-guard, rendered via `numericString` (whole → int) so the bytes
        // match the interpreter (raw `/`/`%` would truncate integers and trap on zero).
        case "dividedBy": return "Plume.numericString(Plume.dividedBy(Double(\(value)), Double(\(try argument(0)))))"
        case "modulo": return "Plume.numericString(Plume.modulo(Double(\(value)), Double(\(try argument(0)))))"
        case "abs": return "Swift.abs(\(value))"
        case "atLeast": return "Swift.max(\(value), \(try argument(0)))"
        case "atMost": return "Swift.min(\(value), \(try argument(0)))"
        // `round` honors an optional precision argument (0 when omitted), like the interpreter.
        case "round": return "Plume.numericString(Plume.rounded(Double(\(value)), Double(\(lowered.first ?? "0"))))"
        case "ceil": return "Int((\(value)).rounded(.up))"
        case "floor": return "Int((\(value)).rounded(.down))"
        case "default": return "Plume.defaulted(\(value), \(try argument(0)))"
        default:
            throw PlumeError.template(
                "The filter `\(name)` is build-time-only (it relies on Foundation or Unicode) and is not available in the compiling back-end.",
                context: context)
        }
    }

    func parseFilter(_ filter: String) -> (name: String, arguments: [String]) {
        let trimmed = filter.trimmingCharacters(in: .whitespacesAndNewlines)
        guard let open = trimmed.firstIndex(of: "("), trimmed.hasSuffix(")") else {
            return (trimmed, [])
        }
        let name = String(trimmed[..<open]).trimmingCharacters(in: .whitespacesAndNewlines)
        let inner = String(
            trimmed[trimmed.index(after: open)..<trimmed.index(before: trimmed.endIndex)])
        let arguments = PlumeSwiftScanning.splitTopLevel(inner, separator: ",").filter {
            !$0.isEmpty
        }
        return (name, arguments)
    }

    // MARK: - Control flow (step 2)

    /// Builds an `if`/`else if` header, recognising `@if let name = expr` as a
    /// Swift optional binding (shared with the interpreting renderer).
    private func conditionHeader(_ condition: String, keyword: String, context: PlumeSourceContext?)
        throws -> String
    {
        if let binding = PlumeConditionParsing.optionalBinding(in: condition) {
            let expression = try PlumeSwiftExpression(context: context).lower(binding.expression)
            return "\(keyword) let \(binding.name) = \(expression) {"
        }
        let lowered = try PlumeSwiftExpression(context: context).lowerCondition(condition)
        // Route through Plume.truthy so documented truthiness holds for String/
        // optional/array conditions (Bool passes through untouched).
        return "\(keyword) Plume.truthy(\(lowered)) {"
    }

    mutating func lowerConditional(
        condition: String, body: [PlumeNode], alternate: [PlumeNode], context: PlumeSourceContext?
    ) throws {
        locatedLine(try conditionHeader(condition, keyword: "if", context: context), context: context)
        indentationLevel += 1
        try lowerNodes(body)
        indentationLevel -= 1
        // `else if` chains: a single trailing conditional collapses to `else if`.
        if alternate.count == 1, case .conditional(let elseCondition, let elseBody, let elseAlt, let elseContext) = alternate[0] {
            locatedLine(
                try conditionHeader(elseCondition, keyword: "} else if", context: elseContext),
                context: elseContext)
            indentationLevel += 1
            try lowerNodes(elseBody)
            indentationLevel -= 1
            try lowerConditionalTail(elseAlt)
        } else if !alternate.isEmpty {
            line("} else {")
            indentationLevel += 1
            try lowerNodes(alternate)
            indentationLevel -= 1
            line("}")
        } else {
            line("}")
        }
    }

    /// Emits the tail of an `else if` chain (a nested alternate already opened).
    private mutating func lowerConditionalTail(_ alternate: [PlumeNode]) throws {
        if alternate.count == 1, case .conditional(let condition, let body, let alt, let context) = alternate[0] {
            locatedLine(
                try conditionHeader(condition, keyword: "} else if", context: context),
                context: context)
            indentationLevel += 1
            try lowerNodes(body)
            indentationLevel -= 1
            try lowerConditionalTail(alt)
        } else if !alternate.isEmpty {
            line("} else {")
            indentationLevel += 1
            try lowerNodes(alternate)
            indentationLevel -= 1
            line("}")
        } else {
            line("}")
        }
    }

    mutating func lowerLoop(
        variable: String, collection: String, body: [PlumeNode], context: PlumeSourceContext?
    ) throws {
        let lowerer = PlumeSwiftExpression(context: context)
        let swiftCollection = try lowerer.lower(collection)
        if referencesForLoop(in: body) {
            let sequence = nextTemporary("seq")
            let index = nextTemporary("i")
            locatedLine("let \(sequence) = Array(\(swiftCollection))", context: context)
            line("for (\(index), \(variable)) in \(sequence).enumerated() {")
            indentationLevel += 1
            line("let forloop = PlumeForLoop(index: \(index), count: \(sequence).count)")
            line("_ = forloop")
            try lowerNodes(body)
            indentationLevel -= 1
            line("}")
        } else {
            locatedLine("for \(variable) in \(swiftCollection) {", context: context)
            indentationLevel += 1
            try lowerNodes(body)
            indentationLevel -= 1
            line("}")
        }
    }

    mutating func lowerAssign(name: String, expression: String, context: PlumeSourceContext?) throws {
        let lowerer = PlumeSwiftExpression(context: context)
        let value = try lowerer.lower(expression)
        locatedLine("let \(name) = \(value)", context: context)
        line("_ = \(name)")
    }

    // MARK: - Components & slots (step 3)

    mutating func lowerComponentCall(
        name: String, arguments: [PlumeArgument], body: [PlumeNode], context: PlumeSourceContext?
    ) throws {
        guard let component = components[name] else {
            throw PlumeError.template(
                "Unknown Plume component: \(name).", context: context)
        }

        // Resolve provided prop values, mapping positional arguments to parameter
        // names. Swift requires arguments in declaration order with labels, so we
        // emit them in `component.parameters` order regardless of call order.
        let lowerer = PlumeSwiftExpression(context: context)
        var providedProps: [String: String] = [:]
        var positionalIndex = 0
        for argument in arguments {
            let value = try lowerer.lower(argument.expression)
            if let label = argument.label {
                providedProps[label] = value
            } else {
                guard positionalIndex < component.parameters.count else {
                    throw PlumeError.template(
                        "Too many arguments for component \(component.name).", context: context)
                }
                providedProps[component.parameters[positionalIndex].name] = value
                positionalIndex += 1
            }
        }

        // Split the call body into the default slot (everything that is not an
        // @content block) and the named slots.
        var namedSlotBodies: [String: [PlumeNode]] = [:]
        var defaultSlotBody: [PlumeNode] = []
        for node in body {
            if case .content(let slotName, let slotBody, _) = node {
                namedSlotBodies[slotName] = slotBody
            } else {
                defaultSlotBody.append(node)
            }
        }

        var argumentStrings: [String] = []
        for parameter in component.parameters {
            if let value = providedProps[parameter.name] {
                argumentStrings.append("\(parameter.name): \(value)")
            }
        }
        for slot in slotParameters(of: component) {
            let slotNodes: [PlumeNode]?
            if slot.isDefault {
                slotNodes = hasRenderableContent(defaultSlotBody) ? defaultSlotBody : nil
            } else {
                slotNodes = namedSlotBodies[slot.rawName ?? ""]
            }
            guard let slotNodes else { continue }
            let fragment = try renderFragment(slotNodes, indentationLevel: indentationLevel + 1)
            let closure = "{ out in\n\(fragment)\(indentString(indentationLevel)) }"
            argumentStrings.append("\(slot.swiftName): \(closure)")
        }
        argumentStrings.append("into: &out")

        let call = "\(functionName(name))(\(argumentStrings.joined(separator: ", ")))"
        // A slot-free call fits on one line and maps cleanly to the call site.
        // Slot closures contain their own (location-free) statements, so the whole
        // multi-line call is emitted as a single unit.
        line(call)
    }

    mutating func lowerSlot(name: String?, fallback: [PlumeNode], context: PlumeSourceContext?) throws {
        let slot = slotParameter(forName: name)
        // Render the provided slot into a buffer and fall back when it's EMPTY — not
        // merely when it's absent — so a slot that renders to nothing (e.g. `{x}` with
        // an empty x) shows the fallback, matching the interpreter.
        let buffer = nextTemporary("slot")
        line("var \(buffer) = HTML()")
        line("if let \(slot.swiftName) { \(slot.swiftName)(&\(buffer)) }")
        line("if \(buffer).bytes.isEmpty {")
        indentationLevel += 1
        if !fallback.isEmpty { try lowerNodes(fallback) }
        indentationLevel -= 1
        line("} else {")
        indentationLevel += 1
        line("out.append(\(buffer).bytes)")
        // Carry over asset requirements (a `@style`/`@script` component in the slot),
        // which `append([UInt8])` alone wouldn't propagate out of the buffer.
        line("if let __href = \(buffer).stylesheetHref { out.requireStylesheet(__href) }")
        line("if let __href = \(buffer).scriptHref { out.requireScript(__href) }")
        indentationLevel -= 1
        line("}")
    }

    /// Renders `nodes` with a nested generator and returns the statements (no
    /// function wrapper, no header). Source locations are disabled inside slot
    /// closures so directives never land mid-expression.
    private func renderFragment(_ nodes: [PlumeNode], indentationLevel: Int) throws -> String {
        var fragmentOptions = options
        fragmentOptions.emitSourceLocations = false
        var sub = PlumeSwiftGenerator(components: components, options: fragmentOptions)
        sub.indentationLevel = indentationLevel
        try sub.lowerNodes(nodes)
        return sub.output
    }

    private func indentString(_ level: Int) -> String {
        String(repeating: "    ", count: level)
    }

    // MARK: - Slot discovery

    struct SlotParameter {
        var rawName: String?
        var swiftName: String
        var isDefault: Bool { rawName == nil }
    }

    /// The ordered, de-duplicated slots a component exposes: the default slot (if
    /// any) first, then named slots in first-appearance order.
    func slotParameters(of component: PlumeComponent) -> [SlotParameter] {
        var hasDefault = false
        var namedOrder: [String] = []
        var seenNamed = Set<String>()
        collectSlots(in: component.body, hasDefault: &hasDefault, namedOrder: &namedOrder, seen: &seenNamed)
        var result: [SlotParameter] = []
        if hasDefault {
            result.append(slotParameter(forName: nil))
        }
        for name in namedOrder {
            result.append(slotParameter(forName: name))
        }
        return result
    }

    private func collectSlots(
        in nodes: [PlumeNode], hasDefault: inout Bool, namedOrder: inout [String],
        seen: inout Set<String>
    ) {
        for node in nodes {
            switch node {
            case .slot(let name, let fallback, _):
                if let name {
                    if seen.insert(name).inserted { namedOrder.append(name) }
                } else {
                    hasDefault = true
                }
                collectSlots(in: fallback, hasDefault: &hasDefault, namedOrder: &namedOrder, seen: &seen)
            case .conditional(_, let body, let alternate, _):
                collectSlots(in: body, hasDefault: &hasDefault, namedOrder: &namedOrder, seen: &seen)
                collectSlots(in: alternate, hasDefault: &hasDefault, namedOrder: &namedOrder, seen: &seen)
            case .loop(_, _, let body, _):
                collectSlots(in: body, hasDefault: &hasDefault, namedOrder: &namedOrder, seen: &seen)
            case .componentCall(_, _, let body, _):
                // A nested call's own body fills *its* slots, not ours.
                _ = body
            default:
                continue
            }
        }
    }

    func slotParameter(forName name: String?) -> SlotParameter {
        guard let name else {
            return SlotParameter(rawName: nil, swiftName: "slot")
        }
        return SlotParameter(rawName: name, swiftName: swiftSlotIdentifier(name))
    }

    /// Turns a Plume slot name into a valid Swift identifier (hyphens become
    /// underscores; Swift keywords are back-ticked).
    private func swiftSlotIdentifier(_ name: String) -> String {
        let sanitized = name.replacingOccurrences(of: "-", with: "_")
        if Self.swiftKeywords.contains(sanitized) {
            return "`\(sanitized)`"
        }
        return sanitized
    }

    private static let swiftKeywords: Set<String> = [
        "default", "class", "struct", "enum", "func", "let", "var", "if", "else", "for", "while",
        "return", "self", "init", "protocol", "extension", "where", "in", "do", "case", "switch",
        "guard", "defer", "true", "false", "nil", "import", "static", "public", "private",
    ]

    /// True when slot/call body content is more than insignificant whitespace.
    private func hasRenderableContent(_ nodes: [PlumeNode]) -> Bool {
        for node in nodes {
            if case .text(let text) = node {
                if !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty { return true }
            } else {
                return true
            }
        }
        return false
    }

    // MARK: - forloop detection

    private func referencesForLoop(in nodes: [PlumeNode]) -> Bool {
        for node in nodes {
            switch node {
            case .output(let expression, _):
                if mentionsForLoop(expression) { return true }
            case .assign(_, let expression, _):
                if mentionsForLoop(expression) { return true }
            case .conditional(let condition, let body, let alternate, _):
                if mentionsForLoop(condition) || referencesForLoop(in: body)
                    || referencesForLoop(in: alternate) { return true }
            case .componentCall(_, let arguments, let body, _):
                if arguments.contains(where: { mentionsForLoop($0.expression) })
                    || referencesForLoop(in: body) { return true }
            case .slot(_, let fallback, _):
                if referencesForLoop(in: fallback) { return true }
            case .content(_, let body, _):
                if referencesForLoop(in: body) { return true }
            case .loop:
                // A nested loop shadows `forloop`; its own detection handles it.
                continue
            default:
                continue
            }
        }
        return false
    }

    private func mentionsForLoop(_ expression: String) -> Bool {
        guard let range = expression.range(of: "forloop") else { return false }
        let before = range.lowerBound == expression.startIndex
            ? nil : expression[expression.index(before: range.lowerBound)]
        let after = range.upperBound == expression.endIndex
            ? nil : expression[range.upperBound]
        let boundaryBefore = before.map { !($0.isLetter || $0.isNumber || $0 == "_") } ?? true
        let boundaryAfter = after.map { !($0.isLetter || $0.isNumber || $0 == "_") } ?? true
        return boundaryBefore && boundaryAfter
    }

    // MARK: - Behaviour hooks

    /// The scope attribute names for a component's scoped `@style` declarations.
    private func scopeAttributes(in nodes: [PlumeNode]) -> [String] {
        var attributes: [String] = []
        var seen = Set<String>()
        collectScopeAttributes(in: nodes, into: &attributes, seen: &seen)
        return attributes
    }

    private func collectScopeAttributes(
        in nodes: [PlumeNode], into attributes: inout [String], seen: inout Set<String>
    ) {
        for node in nodes {
            switch node {
            case .style(let declaration) where declaration.scoped:
                let scope = PlumeScope.styleScope(
                    sourceName: declaration.sourceName, context: declaration.context,
                    css: declaration.css, file: declaration.file)
                let attribute = PlumeScope.attribute(for: scope)
                if seen.insert(attribute).inserted { attributes.append(attribute) }
            case .conditional(_, let body, let alternate, _):
                collectScopeAttributes(in: body, into: &attributes, seen: &seen)
                collectScopeAttributes(in: alternate, into: &attributes, seen: &seen)
            case .loop(_, _, let body, _):
                collectScopeAttributes(in: body, into: &attributes, seen: &seen)
            default:
                continue
            }
        }
    }

    /// Inserts the scope attributes immediately after each opening tag's name.
    /// Operates on a single static text node: the tag name always lives in static
    /// text (interpolation can only appear in attribute values, which follow the
    /// name), so a tag split across an interpolation is still scoped correctly.
    static func applyScopeAttributes(to text: String, attributes: [String]) -> String {
        let insertion = " " + attributes.joined(separator: " ")
        var output = ""
        output.reserveCapacity(text.count + insertion.count)
        var index = text.startIndex
        while index < text.endIndex {
            let character = text[index]
            output.append(character)
            index = text.index(after: index)
            guard character == "<", index < text.endIndex else { continue }
            let first = text[index]
            guard first.isLetter || first == "_" else { continue }  // skip </, <!, <?
            // Copy the tag name, then splice the scope attributes in after it.
            while index < text.endIndex,
                text[index].isLetter || text[index].isNumber || text[index] == "-"
                    || text[index] == "_" || text[index] == ":"
            {
                output.append(text[index])
                index = text.index(after: index)
            }
            output.append(contentsOf: insertion)
        }
        return output
    }

    /// Emits the `<script data-plume-state>` hook with each `@state` value's
    /// JSON-encoded initial value, computed from props at render time.
    private mutating func emitStateHook(for body: [PlumeNode]) throws {
        let states = stateDeclarations(in: body)
        guard !states.isEmpty else { return }
        // The client runtime reads this hook, so a page with @state needs the bundle.
        line("out.requireScript(asset(\"app.js\"))")
        line(
            "out.literal(\(swiftStringLiteral("<script type=\"application/json\" data-plume-state>{")))"
        )
        for (offset, state) in states.enumerated() {
            let prefix = offset == 0 ? "" : ","
            line("out.literal(\(swiftStringLiteral("\(prefix)\"\(state.name)\":")))")
            let value = try PlumeSwiftExpression(context: state.context).lower(state.expression)
            line("out.jsonValue(\(value))")
        }
        line("out.literal(\(swiftStringLiteral("}</script>")))")
    }

    private func stateDeclarations(in nodes: [PlumeNode])
        -> [(name: String, expression: String, context: PlumeSourceContext?)]
    {
        var states: [(name: String, expression: String, context: PlumeSourceContext?)] = []
        for node in nodes {
            if case .state(let name, let expression, let context) = node {
                states.append((name, expression, context))
            }
        }
        return states
    }

    /// Emits the static `<script data-plume-navigation>` configuration marker the
    /// client runtime reads. The config is fully known at compile time.
    private mutating func emitNavigationMarker(_ resource: PlumeNavigationResource) {
        var hooks = "{"
        for (offset, hook) in resource.hooks.enumerated() {
            if offset > 0 { hooks += "," }
            let actions = hook.actions.map { jsonStringLiteral($0) }.joined(separator: ",")
            hooks += "\(jsonStringLiteral(hook.name)):[\(actions)]"
        }
        hooks += "}"
        let config =
            "{\"root\":\(jsonStringLiteral(resource.root)),"
            + "\"viewTransitions\":\(resource.viewTransitions),"
            + "\"scroll\":\(jsonStringLiteral(resource.scroll)),"
            + "\"minimumDuration\":\(resource.minimumDuration),"
            + "\"progressBar\":\(resource.progressBar),"
            + "\"progressBarDelay\":\(resource.progressBarDelay),"
            + "\"hooks\":\(hooks)}"
        let marker = "<script type=\"application/json\" data-plume-navigation>[\(config)]</script>"
        line("out.literal(\(swiftStringLiteral(marker)))")
        // The page opted into navigation, so it needs the client runtime — recorded
        // here, spliced into <head> at the response boundary. The author writes
        // @navigation, never a manual <script> (matching the interpreter's
        // `requiresRuntime` contract).
        line("out.requireScript(asset(\"app.js\"))")
    }

    /// A compile-time JSON string literal (for static marker encoding).
    private func jsonStringLiteral(_ value: String) -> String {
        var output = "\""
        for scalar in value.unicodeScalars {
            switch scalar {
            case "\\": output += "\\\\"
            case "\"": output += "\\\""
            case "\n": output += "\\n"
            case "\r": output += "\\r"
            case "\t": output += "\\t"
            case "<": output += "\\u003c"
            default: output.unicodeScalars.append(scalar)
            }
        }
        output += "\""
        return output
    }

    // MARK: - #sourceLocation

    /// Emits a single line wrapped in `#sourceLocation` directives so `swiftc`
    /// reports its location against the `.plume` source rather than generated Swift.
    private mutating func locatedLine(_ text: String, context: PlumeSourceContext?) {
        guard options.emitSourceLocations, let context else {
            line(text)
            return
        }
        let path = options.sourcePath ?? context.sourceName ?? "template.plume"
        // Swift derives `#fileID` from the directive's BASENAME, so two templates
        // named e.g. Index.plume in different folders would collide and warn on
        // every directive. Flatten the path the same way generated filenames are
        // flattened (Views/Sessions/Index.plume → Views.Sessions.Index.plume) —
        // unique per template, and still names the source unambiguously.
        let fileIDSafePath = String(path.map { $0 == "/" ? "." : $0 })
        rawLine("#sourceLocation(file: \(swiftStringLiteral(fileIDSafePath)), line: \(context.line))")
        line(text)
        rawLine("#sourceLocation()")
    }

    // MARK: - Emission helpers

    mutating func line(_ text: String) {
        if text.isEmpty {
            output += "\n"
        } else {
            output += String(repeating: "    ", count: indentationLevel) + text + "\n"
        }
    }

    /// Emits a line flush-left (column 0), required for `#sourceLocation`.
    mutating func rawLine(_ text: String) {
        output += text + "\n"
    }

    mutating func nextTemporary(_ stem: String) -> String {
        defer { uniqueCounter += 1 }
        return "__plume_\(stem)_\(uniqueCounter)"
    }

    func swiftStringLiteral(_ value: String) -> String {
        var output = "\""
        for scalar in value.unicodeScalars {
            switch scalar {
            case "\\": output += "\\\\"
            case "\"": output += "\\\""
            case "\n": output += "\\n"
            case "\r": output += "\\r"
            case "\t": output += "\\t"
            case "\0": output += "\\0"
            default: output.unicodeScalars.append(scalar)
            }
        }
        output += "\""
        return output
    }

    func outOfSubset(_ feature: String, context: PlumeSourceContext?) -> PlumeError {
        PlumeError.template(
            "\(feature) is a build-time feature and cannot be lowered into a request-time render function.",
            context: context)
    }
}
