// swift-tools-version:6.2
import PackageDescription

// The "Hello" dogfood app — a normal PlumeKit application: one library of routes
// (`App`) consumed by three thin entry points —
//   • `Server` — native HTTP server for `plumekit serve` and local dev
//   • `Worker` — Embedded-Swift Wasm entry for `plumekit build --target cloudflare`
//   • `Lambda` — AWS Lambda front-end (native binary)
// All call the same `buildApp()`, so the routes are identical across runtimes.
//
// It depends on the framework by relative path; a real app generated by
// `plumekit new` would instead depend on a tagged release of the PlumeKit package.
let package = Package(
    name: "Hello",
    platforms: [.macOS(.v14)],
    products: [
        .executable(name: "Server", targets: ["Server"]),
        .executable(name: "Worker", targets: ["Worker"]),
    ],
    dependencies: [
        // The single merged PlumeKit package (framework + templating). The app
        // depends only on the Embedded-clean PlumeRuntime for rendering; PlumeCore /
        // PlumeORM for the framework. `name:` pins the identity to PlumeKit (the repo
        // dir is `plume`).
        .package(name: "PlumeKit", path: "../.."),
    ],
    targets: [
        .target(
            name: "App",
            dependencies: [
                .product(name: "PlumeCore", package: "PlumeKit"),
                .product(name: "PlumeORM", package: "PlumeKit"),
                .product(name: "PlumeRuntime", package: "PlumeKit"),
            ],
            // Generates the typed `Bindings` (capability gate) from plumekit.toml.
            plugins: [.plugin(name: "PlumeKitCodegen", package: "PlumeKit")]
        ),
        .executableTarget(
            name: "Server",
            dependencies: [
                "App",
                .product(name: "PlumeServer", package: "PlumeKit"),
                // The portability fixture declares the union of adapter deps; the
                // plumekit.toml manifest SELECTS which the composition wires in.
                .product(name: "PlumePostgres", package: "PlumeKit"),
                .product(name: "PlumeS3", package: "PlumeKit"),
            ],
            // Generates the native `Composition` root from plumekit.toml.
            plugins: [.plugin(name: "PlumeKitCodegen", package: "PlumeKit")]
        ),
        // The reactor linker flags for the Wasm build are supplied by
        // `plumekit build` on the command line, so a plain `swift build` stays happy.
        .executableTarget(
            name: "Worker",
            dependencies: [
                "App",
                .product(name: "PlumeWorker", package: "PlumeKit"),
            ]
        ),
        // The AWS Lambda front-end: the SAME App, the AWS adapter set. The AWS
        // composition root is generated from plumekit.toml's [targets.aws] profile.
        .executableTarget(
            name: "Lambda",
            dependencies: [
                "App",
                .product(name: "PlumeAWS", package: "PlumeKit"),
                .product(name: "PlumePostgres", package: "PlumeKit"),
                .product(name: "PlumeS3", package: "PlumeKit"),
            ],
            plugins: [.plugin(name: "PlumeKitCodegen", package: "PlumeKit")]
        ),
    ]
)
