import PlumeCore
import _Concurrency

// The typed query builder. Everything is a CONCRETE generic value type — no
// existentials, Embedded-clean. `Column<Root, Value>` carries the column's Swift
// type, so operators only type-check against matching values: `Post.published > 100`
// fails to COMPILE (Bool isn't Comparable / Int ≠ Bool). Predicates lower to
// PARAMETERISED SQL ("views > ?"); values are always bound, never interpolated.
// Text collation/ordering is delegated to the database (the guest has no Unicode
// tables) — we only emit ASCII column names + operators.

/// A value that can be bound as a SQL parameter.
public protocol SQLValueConvertible {
    var asSQLValue: SQLValue { get }
}
extension Int: SQLValueConvertible { public var asSQLValue: SQLValue { sqlInt(self) } }
extension Int64: SQLValueConvertible { public var asSQLValue: SQLValue { sqlInt(self) } }
extension UUID: SQLValueConvertible { public var asSQLValue: SQLValue { sqlUUID(self) } }
extension String: SQLValueConvertible { public var asSQLValue: SQLValue { sqlText(self) } }
extension Bool: SQLValueConvertible { public var asSQLValue: SQLValue { sqlBool(self) } }
extension Double: SQLValueConvertible { public var asSQLValue: SQLValue { sqlReal(self) } }
/// An already-encoded value passes through — lets a relation `find` by a raw
/// `primaryKeyValue`/FK of any key type (Int, UUID, String).
extension SQLValue: SQLValueConvertible { public var asSQLValue: SQLValue { self } }

/// A typed reference to a column of `Root`. Generated by @Model as `static let`s.
/// `Root`/`Value` are phantom (only the ASCII `name` is stored), so this is safely
/// `Sendable` regardless of them.
public struct Column<Root, Value>: @unchecked Sendable {
    public let name: String
    public init(_ name: String) { self.name = name }
}

/// A parameterised boolean expression over `Root`. Concrete value type.
public struct Predicate<Root> {
    public let sql: String
    public let bindings: [SQLValue]
    public init(sql: String, bindings: [SQLValue]) {
        self.sql = sql
        self.bindings = bindings
    }
}

public enum SortDirection: Sendable { case ascending, descending }

// MARK: - Comparison operators (Column ⊕ Value → Predicate)

public func == <Root, Value: SQLValueConvertible>(lhs: Column<Root, Value>, rhs: Value) -> Predicate<Root> {
    Predicate(sql: lhs.name + " = ?", bindings: [rhs.asSQLValue])
}
public func != <Root, Value: SQLValueConvertible>(lhs: Column<Root, Value>, rhs: Value) -> Predicate<Root> {
    Predicate(sql: lhs.name + " <> ?", bindings: [rhs.asSQLValue])
}
public func > <Root, Value: SQLValueConvertible & Comparable>(lhs: Column<Root, Value>, rhs: Value) -> Predicate<Root> {
    Predicate(sql: lhs.name + " > ?", bindings: [rhs.asSQLValue])
}
public func < <Root, Value: SQLValueConvertible & Comparable>(lhs: Column<Root, Value>, rhs: Value) -> Predicate<Root> {
    Predicate(sql: lhs.name + " < ?", bindings: [rhs.asSQLValue])
}
public func >= <Root, Value: SQLValueConvertible & Comparable>(lhs: Column<Root, Value>, rhs: Value) -> Predicate<Root> {
    Predicate(sql: lhs.name + " >= ?", bindings: [rhs.asSQLValue])
}
public func <= <Root, Value: SQLValueConvertible & Comparable>(lhs: Column<Root, Value>, rhs: Value) -> Predicate<Root> {
    Predicate(sql: lhs.name + " <= ?", bindings: [rhs.asSQLValue])
}

// MARK: - Logical combinators (Predicate ⊕ Predicate → Predicate)

extension Column where Value: SQLValueConvertible {
    /// `column IN (…)` — the batching primitive: a page preloads an association
    /// set in ONE query instead of one per row. An empty list matches nothing.
    public func within(_ values: [Value]) -> Predicate<Root> {
        guard !values.isEmpty else { return Predicate(sql: "1 = 0", bindings: []) }
        return Predicate(sql: name + " IN (" + placeholders(values.count) + ")",
                         bindings: values.map { $0.asSQLValue })
    }
}

public func && <Root>(lhs: Predicate<Root>, rhs: Predicate<Root>) -> Predicate<Root> {
    Predicate(sql: "(" + lhs.sql + ") AND (" + rhs.sql + ")", bindings: lhs.bindings + rhs.bindings)
}
public func || <Root>(lhs: Predicate<Root>, rhs: Predicate<Root>) -> Predicate<Root> {
    Predicate(sql: "(" + lhs.sql + ") OR (" + rhs.sql + ")", bindings: lhs.bindings + rhs.bindings)
}

// MARK: - Query

/// A page of results + pagination metadata. `hasMore` tells a client whether
/// to request the next offset; serialize it via `paginatedJSON` in core.
public struct Page<M: Model> {
    public let items: [M]
    public let limit: Int
    public let offset: Int
    public let hasMore: Bool
    /// The total number of matching rows, when the paginate call asked for it
    /// (`withTotal: true`); nil otherwise (hasMore alone needs no COUNT).
    public let total: Int?

    public init(items: [M], limit: Int, offset: Int, hasMore: Bool, total: Int? = nil) {
        self.items = items
        self.limit = limit
        self.offset = offset
        self.hasMore = hasMore
        self.total = total
    }

    /// The current 1-based page number.
    public var page: Int { offset / max(1, limit) + 1 }
    /// The previous/next page numbers, or nil at the edges.
    public var previousPage: Int? { page > 1 ? page - 1 : nil }
    public var nextPage: Int? { hasMore ? page + 1 : nil }
    /// Total pages, when a total was counted.
    public var totalPages: Int? { total.map { max(1, ($0 + limit - 1) / max(1, limit)) } }

    /// Ready-to-render pagination URLs: `page.nextURL("/posts")` → `/posts?page=3&per=20`.
    /// A path that already carries a query string gets `&` instead of a second `?`.
    public func url(_ path: String, page number: Int) -> String {
        let separator = utf8Contains(path, "?") ? "&" : "?"
        return path + separator + "page=" + String(number) + "&per=" + String(limit)
    }
    public func nextURL(_ path: String) -> String? { nextPage.map { url(path, page: $0) } }
    public func previousURL(_ path: String) -> String? { previousPage.map { url(path, page: $0) } }
}

public struct Query<M: Model> {
    var predicate: Predicate<M>?
    var orderClause: String?
    var limitCount: Int?
    var offsetCount: Int?
    var withoutDefaultScope = false

    public init() {}

    /// Ignore the model's `defaultScope` for this query (e.g. include soft-deleted
    /// rows — `Post.withTrashed()` is sugar for this).
    public func unscoped() -> Query<M> {
        var copy = self
        copy.withoutDefaultScope = true
        return copy
    }

    /// The WHERE predicate terminals run: the model's default scope (unless bypassed)
    /// ANDed with whatever `where` built up.
    var effectivePredicate: Predicate<M>? {
        let scope = withoutDefaultScope ? nil : M.defaultScope
        switch (scope, predicate) {
        case (nil, let built): return built
        case (let scope, nil): return scope
        case (let scope?, let built?): return scope && built
        }
    }

    public func `where`(_ p: Predicate<M>) -> Query<M> {
        var copy = self
        if let existing = predicate {
            copy.predicate = existing && p
        } else {
            copy.predicate = p
        }
        return copy
    }

    /// Add a sort column. Chained calls COMPOSE into a multi-column ORDER BY
    /// (`.order(by: Post.published).order(by: Post.views, .descending)` sorts by
    /// published, then views) — a later call never silently replaces an earlier one.
    public func order<V>(by column: Column<M, V>, _ direction: SortDirection = .ascending) -> Query<M> {
        var copy = self
        let clause = column.name + (direction == .descending ? " DESC" : " ASC")
        copy.orderClause = orderClause.map { $0 + ", " + clause } ?? clause
        return copy
    }

    public func limit(_ count: Int) -> Query<M> {
        var copy = self
        copy.limitCount = count
        return copy
    }

    public func offset(_ count: Int) -> Query<M> {
        var copy = self
        copy.offsetCount = count
        return copy
    }

    /// Execute and decode all matching rows.
    public func all(in db: Database? = nil) async throws -> [M] {
        let db = resolvedDatabase(db)
        let predicate = effectivePredicate
        var sql = "SELECT " + selectColumns(M.schema) + " FROM " + M.schema.table
        if let predicate { sql += " WHERE " + predicate.sql }
        if let orderClause { sql += " ORDER BY " + orderClause }
        if let limitCount { sql += " LIMIT " + integerLiteral(limitCount) }
        else if offsetCount != nil { sql += " LIMIT " + integerLiteral(Int.max) }  // SQLite needs a LIMIT before OFFSET; Int.max = effectively unlimited on both dialects
        if let offsetCount { sql += " OFFSET " + integerLiteral(offsetCount) }
        let result = try await db.query(sql, predicate?.bindings ?? [])
        var models: [M] = []
        for row in result.rows { models.append(M(row: Row(row))) }
        return models
    }

    /// Pagination: a page of results + consistent metadata. Fetches `limit+1`
    /// rows to detect `hasMore` without a second query. Order by a stable column for
    /// deterministic pages. Uses the request's database like every other terminal;
    /// pass `in:` outside a request.
    public func paginate(limit: Int, offset: Int = 0, withTotal: Bool = false,
                         in db: Database? = nil) async throws -> Page<M> {
        let limit = max(1, limit)                 // a non-positive page size is meaningless
        let offset = max(0, offset)
        // Fetch one extra to detect `hasMore`, without overflowing at Int.max.
        let fetchLimit = limit < Int.max ? limit + 1 : limit
        let fetched = try await self.limit(fetchLimit).offset(offset).all(in: db)
        let hasMore = fetched.count > limit
        let total = withTotal ? try await count(in: db) : nil
        return Page(items: hasMore ? Array(fetched.prefix(limit)) : fetched,
                    limit: limit, offset: offset, hasMore: hasMore, total: total)
    }

    /// Page-number pagination (1-based): `Post.query().order(by: Post.id).paginate(page: 2, per: 20)`.
    /// `withTotal: true` also runs a COUNT so the page carries `total`/`totalPages`.
    public func paginate(page: Int, per: Int, withTotal: Bool = false,
                         in db: Database? = nil) async throws -> Page<M> {
        let page = max(1, page)
        let per = max(1, per)
        // Saturate the offset instead of trapping — `page`/`per` come straight from query
        // params, so `(page-1)*per` can overflow (Int is 32-bit on the Wasm guest). An
        // absurd offset just yields an empty page rather than crashing the worker.
        let (product, overflow) = (page - 1).multipliedReportingOverflow(by: per)
        return try await paginate(limit: per, offset: overflow ? Int.max : product, withTotal: withTotal, in: db)
    }

    /// Pagination straight from a request: reads the `page`/`per` query params —
    /// the same names `Page.url`/`nextURL` emit, so the links a page renders and
    /// the params a handler reads are two halves of one feature. `per` is clamped
    /// to `maxPer` (query params are user input).
    ///
    ///     let page = try await Post.query().order(by: Post.id).paginate(request)
    public func paginate(_ request: Request, per defaultPer: Int = 20, maxPer: Int = 100,
                         withTotal: Bool = false, in db: Database? = nil) async throws -> Page<M> {
        let page = request.queryParams.int("page") ?? 1
        let per = min(max(1, maxPer), max(1, request.queryParams.int("per") ?? defaultPer))
        return try await paginate(page: page, per: per, withTotal: withTotal, in: db)
    }

    /// The first matching row, or nil.
    public func first(in db: Database? = nil) async throws -> M? {
        try await limit(1).all(in: db).first
    }

    /// COUNT(*) of matching rows.
    public func count(in db: Database? = nil) async throws -> Int {
        let db = resolvedDatabase(db)
        let predicate = effectivePredicate
        var sql = "SELECT COUNT(*) FROM " + M.schema.table
        if let predicate { sql += " WHERE " + predicate.sql }
        let result = try await db.query(sql, predicate?.bindings ?? [])
        guard let row = result.rows.first else { return 0 }
        return Row(row).int(0)
    }

    /// Whether any row matches — `SELECT 1 … LIMIT 1`, so unlike `count() > 0`
    /// the database stops at the first hit.
    public func exists(in db: Database? = nil) async throws -> Bool {
        let db = resolvedDatabase(db)
        let predicate = effectivePredicate
        var sql = "SELECT 1 FROM " + M.schema.table
        if let predicate { sql += " WHERE " + predicate.sql }
        sql += " LIMIT 1"
        let result = try await db.query(sql, predicate?.bindings ?? [])
        return !result.rows.isEmpty
    }

    /// A single column's values, without decoding whole rows.
    /// `LodgingAssignment.where(…).pluck(LodgingAssignment.user_id)`.
    public func pluck<Value>(_ column: Column<M, Value>,
                             in db: Database? = nil) async throws -> [SQLValue] {
        let db = resolvedDatabase(db)
        let predicate = effectivePredicate
        var sql = "SELECT " + column.name + " FROM " + M.schema.table
        if let predicate { sql += " WHERE " + predicate.sql }
        if let orderClause { sql += " ORDER BY " + orderClause }
        if let limitCount { sql += " LIMIT " + integerLiteral(limitCount) }
        else if offsetCount != nil { sql += " LIMIT " + integerLiteral(Int.max) }  // SQLite: LIMIT must precede OFFSET
        if let offsetCount { sql += " OFFSET " + integerLiteral(offsetCount) }
        let result = try await db.query(sql, predicate?.bindings ?? [])
        return result.rows.map { Row($0).value(0) }
    }

    /// `pluck` for integer columns (the common id/foreign-key case), decoded with
    /// `Row`'s coercions.
    public func pluckInts(_ column: Column<M, Int>,
                          in db: Database? = nil) async throws -> [Int] {
        try await pluck(column, in: db).map { Row([$0]).int(0) }
    }

    // MARK: Bulk writes (one statement, no per-row loads — Rails' delete_all/update_all)

    /// DELETE every matching row in one statement. Respects the model's
    /// `defaultScope` (a soft-deletable model's live rows only — use
    /// `withTrashed().delete()` to purge). Model callbacks do NOT run — this never
    /// loads the rows. Returns the number of rows deleted.
    @discardableResult
    public func delete(in db: Database? = nil) async throws -> Int {
        let db = resolvedDatabase(db)
        let predicate = effectivePredicate
        var sql = "DELETE FROM " + M.schema.table
        if let predicate { sql += " WHERE " + predicate.sql }
        let result = try await db.query(sql, predicate?.bindings ?? [])
        return result.rowsAffected
    }

    /// UPDATE every matching row in one statement:
    /// `Post.where(Post.published == false).updateAll(Post.views.set(0))`.
    /// Like `delete()`, callbacks/validations/timestamps do NOT run. Returns the
    /// number of rows updated.
    @discardableResult
    public func updateAll(_ assignments: Assignment<M>..., in db: Database? = nil) async throws -> Int {
        guard !assignments.isEmpty else { return 0 }
        let db = resolvedDatabase(db)
        let predicate = effectivePredicate
        var setClause = ""
        var bindings: [SQLValue] = []
        for assignment in assignments {
            if !setClause.isEmpty { setClause += ", " }
            setClause += assignment.sql
            bindings.append(contentsOf: assignment.bindings)
        }
        var sql = "UPDATE " + M.schema.table + " SET " + setClause
        if let predicate {
            sql += " WHERE " + predicate.sql
            bindings.append(contentsOf: predicate.bindings)
        }
        let result = try await db.query(sql, bindings)
        return result.rowsAffected
    }

    // MARK: Aggregates (single value, no row decoding)
    // Cells decode through `Row`'s coercions — the one home for SQLValue→number
    // semantics (a backend can hand SUM/AVG back as `.double`; `Row` wraps rather
    // than trapping on out-of-range values).

    /// SUM of an integer column over the matching rows (0 with no rows).
    public func sum(_ column: Column<M, Int>, in db: Database? = nil) async throws -> Int {
        try await aggregate("SUM", column.name, in: db).map { Row([$0]).int(0) } ?? 0
    }

    /// SUM of a real column over the matching rows (0 with no rows).
    public func sum(_ column: Column<M, Double>, in db: Database? = nil) async throws -> Double {
        try await aggregate("SUM", column.name, in: db).map { Row([$0]).double(0) } ?? 0
    }

    /// AVG over the matching rows, or nil with no rows.
    public func average(_ column: Column<M, Int>, in db: Database? = nil) async throws -> Double? {
        try await aggregate("AVG", column.name, in: db).flatMap { Row([$0]).doubleOptional(0) }
    }

    public func average(_ column: Column<M, Double>, in db: Database? = nil) async throws -> Double? {
        try await aggregate("AVG", column.name, in: db).flatMap { Row([$0]).doubleOptional(0) }
    }

    /// MIN/MAX over the matching rows, or nil with no rows.
    public func minimum(_ column: Column<M, Int>, in db: Database? = nil) async throws -> Int? {
        try await aggregate("MIN", column.name, in: db).flatMap { Row([$0]).intOptional(0) }
    }

    public func maximum(_ column: Column<M, Int>, in db: Database? = nil) async throws -> Int? {
        try await aggregate("MAX", column.name, in: db).flatMap { Row([$0]).intOptional(0) }
    }

    public func minimum(_ column: Column<M, Double>, in db: Database? = nil) async throws -> Double? {
        try await aggregate("MIN", column.name, in: db).flatMap { Row([$0]).doubleOptional(0) }
    }

    public func maximum(_ column: Column<M, Double>, in db: Database? = nil) async throws -> Double? {
        try await aggregate("MAX", column.name, in: db).flatMap { Row([$0]).doubleOptional(0) }
    }

    /// The raw aggregate cell (`nil` when SQL returns NULL, e.g. no rows).
    /// `function` and `columnName` are ASCII tokens from typed columns, never user input.
    private func aggregate(_ function: String, _ columnName: String,
                           in db: Database?) async throws -> SQLValue? {
        let db = resolvedDatabase(db)
        let predicate = effectivePredicate
        var sql = "SELECT " + function + "(" + columnName + ") FROM " + M.schema.table
        if let predicate { sql += " WHERE " + predicate.sql }
        let result = try await db.query(sql, predicate?.bindings ?? [])
        guard let row = result.rows.first else { return nil }
        if case .null = row[0] { return nil }
        return row[0]
    }
}

/// A `SET` clause fragment for `updateAll`, built from a typed column:
/// `Post.views.set(0)` → `views = ?`. Value type, Embedded-clean.
public struct Assignment<Root> {
    let sql: String
    let bindings: [SQLValue]
}

extension Column where Value: SQLValueConvertible {
    /// An assignment for `Query.updateAll`: `Post.published.set(true)`.
    public func set(_ value: Value) -> Assignment<Root> {
        Assignment(sql: name + " = ?", bindings: [value.asSQLValue])
    }
}


// MARK: - Model query entry points

extension Model {
    /// Start an unfiltered query builder: `Post.query().order(by: Post.id).all(in: db)`.
    /// (The entry point is `query()` and the executing terminal is `all(in:)`, so
    /// which call hits the database is always visible at the call site.)
    public static func query() -> Query<Self> { Query<Self>() }

    /// Every row, directly: `try await Post.all()` inside a request (ambient
    /// database), `Post.all(in: db)` elsewhere.
    public static func all(in db: Database? = nil) async throws -> [Self] {
        try await Query<Self>().all(in: db)
    }

    /// Every-row COUNT without a builder: `try await Post.count(in: db)`.
    public static func count(in db: Database? = nil) async throws -> Int {
        try await Query<Self>().count(in: db)
    }

    /// Start a filtered query: `Post.where(Post.views > 100)`.
    public static func `where`(_ p: Predicate<Self>) -> Query<Self> {
        Query<Self>().where(p)
    }
}

/// Render an Int as an ASCII decimal literal (LIMIT is a structural literal, not a
/// bound value). Avoids any Unicode-aware String formatting.
func integerLiteral(_ value: Int) -> String {
    String(value)
}

extension Response {
    /// Serialize a `Page` of resources with its pagination metadata:
    /// `{"items": […], "limit": …, "offset": …, "hasMore": …}` — the shape
    /// `paginatedJSON` defines, so hand-rolled and ORM-paginated endpoints match.
    public static func json<M: Model & JSONRepresentable>(_ page: Page<M>, status: Int = 200) -> Response {
        var envelope = paginatedJSON(page.items.map(\.jsonValue), limit: page.limit,
                                     offset: page.offset, hasMore: page.hasMore)
        if case .object(var pairs) = envelope, let total = page.total {
            pairs.append((name: "total", value: .int(Int64(total))))
            pairs.append((name: "page", value: .int(Int64(page.page))))
            envelope = .object(pairs)
        }
        return .json(envelope, status: status)
    }
}
