import PlumeCore
import _Concurrency

// The typed query builder. Everything is a CONCRETE generic value type — no
// existentials, Embedded-clean. `Column<Root, Value>` carries the column's Swift
// type, so operators only type-check against matching values: `Post.published > 100`
// fails to COMPILE (Bool isn't Comparable / Int ≠ Bool). Predicates lower to
// PARAMETERISED SQL ("views > ?"); values are always bound, never interpolated.
// Text collation/ordering is delegated to the database (the guest has no Unicode
// tables) — we only emit ASCII column names + operators.

/// A value that can be bound as a SQL parameter.
public protocol SQLValueConvertible {
    var asSQLValue: SQLValue { get }
}
extension Int: SQLValueConvertible { public var asSQLValue: SQLValue { sqlInt(self) } }
extension Int64: SQLValueConvertible { public var asSQLValue: SQLValue { sqlInt(self) } }
extension UUID: SQLValueConvertible { public var asSQLValue: SQLValue { sqlUUID(self) } }
extension String: SQLValueConvertible { public var asSQLValue: SQLValue { sqlText(self) } }
extension Bool: SQLValueConvertible { public var asSQLValue: SQLValue { sqlBool(self) } }
extension Double: SQLValueConvertible { public var asSQLValue: SQLValue { sqlReal(self) } }
/// An already-encoded value passes through — lets a relation `find` by a raw
/// `primaryKeyValue`/FK of any key type (Int, UUID, String).
extension SQLValue: SQLValueConvertible { public var asSQLValue: SQLValue { self } }

/// A typed reference to a column of `Root`. Generated by @Model as `static let`s.
/// `Root`/`Value` are phantom (only the ASCII `name` is stored), so this is safely
/// `Sendable` regardless of them.
public struct Column<Root, Value>: @unchecked Sendable {
    public let name: String
    public init(_ name: String) { self.name = name }
}

/// A parameterised boolean expression over `Root`. Concrete value type.
public struct Predicate<Root> {
    public let sql: String
    public let bindings: [SQLValue]
    public init(sql: String, bindings: [SQLValue]) {
        self.sql = sql
        self.bindings = bindings
    }
}

public enum SortDirection: Sendable { case ascending, descending }

// MARK: - Comparison operators (Column ⊕ Value → Predicate)

public func == <Root, Value: SQLValueConvertible>(lhs: Column<Root, Value>, rhs: Value) -> Predicate<Root> {
    Predicate(sql: lhs.name + " = ?", bindings: [rhs.asSQLValue])
}
public func != <Root, Value: SQLValueConvertible>(lhs: Column<Root, Value>, rhs: Value) -> Predicate<Root> {
    Predicate(sql: lhs.name + " <> ?", bindings: [rhs.asSQLValue])
}
public func > <Root, Value: SQLValueConvertible & Comparable>(lhs: Column<Root, Value>, rhs: Value) -> Predicate<Root> {
    Predicate(sql: lhs.name + " > ?", bindings: [rhs.asSQLValue])
}
public func < <Root, Value: SQLValueConvertible & Comparable>(lhs: Column<Root, Value>, rhs: Value) -> Predicate<Root> {
    Predicate(sql: lhs.name + " < ?", bindings: [rhs.asSQLValue])
}
public func >= <Root, Value: SQLValueConvertible & Comparable>(lhs: Column<Root, Value>, rhs: Value) -> Predicate<Root> {
    Predicate(sql: lhs.name + " >= ?", bindings: [rhs.asSQLValue])
}
public func <= <Root, Value: SQLValueConvertible & Comparable>(lhs: Column<Root, Value>, rhs: Value) -> Predicate<Root> {
    Predicate(sql: lhs.name + " <= ?", bindings: [rhs.asSQLValue])
}

// MARK: - Logical combinators (Predicate ⊕ Predicate → Predicate)

public func && <Root>(lhs: Predicate<Root>, rhs: Predicate<Root>) -> Predicate<Root> {
    Predicate(sql: "(" + lhs.sql + ") AND (" + rhs.sql + ")", bindings: lhs.bindings + rhs.bindings)
}
public func || <Root>(lhs: Predicate<Root>, rhs: Predicate<Root>) -> Predicate<Root> {
    Predicate(sql: "(" + lhs.sql + ") OR (" + rhs.sql + ")", bindings: lhs.bindings + rhs.bindings)
}

// MARK: - Query

/// A page of results + pagination metadata. `hasMore` tells a client whether
/// to request the next offset; serialize it via `paginatedJSON` in core.
public struct Page<M: Model> {
    public let items: [M]
    public let limit: Int
    public let offset: Int
    public let hasMore: Bool
    /// The total number of matching rows, when the paginate call asked for it
    /// (`withTotal: true`); nil otherwise (hasMore alone needs no COUNT).
    public let total: Int?

    public init(items: [M], limit: Int, offset: Int, hasMore: Bool, total: Int? = nil) {
        self.items = items
        self.limit = limit
        self.offset = offset
        self.hasMore = hasMore
        self.total = total
    }

    /// The current 1-based page number.
    public var page: Int { offset / max(1, limit) + 1 }
    /// The previous/next page numbers, or nil at the edges.
    public var previousPage: Int? { page > 1 ? page - 1 : nil }
    public var nextPage: Int? { hasMore ? page + 1 : nil }
    /// Total pages, when a total was counted.
    public var totalPages: Int? { total.map { max(1, ($0 + limit - 1) / max(1, limit)) } }

    /// Ready-to-render pagination URLs: `page.nextURL("/posts")` → `/posts?page=3&per=20`.
    /// A path that already carries a query string gets `&` instead of a second `?`.
    public func url(_ path: String, page number: Int) -> String {
        let separator = utf8Contains(path, "?") ? "&" : "?"
        return path + separator + "page=" + String(number) + "&per=" + String(limit)
    }
    public func nextURL(_ path: String) -> String? { nextPage.map { url(path, page: $0) } }
    public func previousURL(_ path: String) -> String? { previousPage.map { url(path, page: $0) } }
}

public struct Query<M: Model> {
    var predicate: Predicate<M>?
    var orderClause: String?
    var limitCount: Int?
    var offsetCount: Int?
    var withoutDefaultScope = false

    public init() {}

    /// Ignore the model's `defaultScope` for this query (e.g. include soft-deleted
    /// rows — `Post.withTrashed()` is sugar for this).
    public func unscoped() -> Query<M> {
        var copy = self
        copy.withoutDefaultScope = true
        return copy
    }

    /// The WHERE predicate terminals run: the model's default scope (unless bypassed)
    /// ANDed with whatever `where` built up.
    var effectivePredicate: Predicate<M>? {
        let scope = withoutDefaultScope ? nil : M.defaultScope
        switch (scope, predicate) {
        case (nil, let built): return built
        case (let scope, nil): return scope
        case (let scope?, let built?): return scope && built
        }
    }

    public func `where`(_ p: Predicate<M>) -> Query<M> {
        var copy = self
        if let existing = predicate {
            copy.predicate = existing && p
        } else {
            copy.predicate = p
        }
        return copy
    }

    public func order<V>(by column: Column<M, V>, _ direction: SortDirection = .ascending) -> Query<M> {
        var copy = self
        let dir = direction == .descending ? " DESC" : " ASC"
        copy.orderClause = column.name + dir
        return copy
    }

    public func limit(_ count: Int) -> Query<M> {
        var copy = self
        copy.limitCount = count
        return copy
    }

    public func offset(_ count: Int) -> Query<M> {
        var copy = self
        copy.offsetCount = count
        return copy
    }

    /// Execute and decode all matching rows.
    public func all(in db: Database? = nil) async throws -> [M] {
        let db = resolvedDatabase(db)
        let predicate = effectivePredicate
        var sql = "SELECT " + selectColumns(M.schema) + " FROM " + M.schema.table
        if let predicate { sql += " WHERE " + predicate.sql }
        if let orderClause { sql += " ORDER BY " + orderClause }
        if let limitCount { sql += " LIMIT " + integerLiteral(limitCount) }
        else if offsetCount != nil { sql += " LIMIT " + integerLiteral(Int.max) }  // SQLite needs a LIMIT before OFFSET; Int.max = effectively unlimited on both dialects
        if let offsetCount { sql += " OFFSET " + integerLiteral(offsetCount) }
        let result = try await db.query(sql, predicate?.bindings ?? [])
        var models: [M] = []
        for row in result.rows { models.append(M(row: Row(row))) }
        return models
    }

    /// Pagination: a page of results + consistent metadata. Fetches `limit+1`
    /// rows to detect `hasMore` without a second query. Order by a stable column for
    /// deterministic pages. Uses the request's database like every other terminal;
    /// pass `in:` outside a request.
    public func paginate(limit: Int, offset: Int = 0, withTotal: Bool = false,
                         in db: Database? = nil) async throws -> Page<M> {
        let limit = max(1, limit)                 // a non-positive page size is meaningless
        let offset = max(0, offset)
        // Fetch one extra to detect `hasMore`, without overflowing at Int.max.
        let fetchLimit = limit < Int.max ? limit + 1 : limit
        let fetched = try await self.limit(fetchLimit).offset(offset).all(in: db)
        let hasMore = fetched.count > limit
        let total = withTotal ? try await count(in: db) : nil
        return Page(items: hasMore ? Array(fetched.prefix(limit)) : fetched,
                    limit: limit, offset: offset, hasMore: hasMore, total: total)
    }

    /// Page-number pagination (1-based): `Post.all().order(by: Post.id).paginate(page: 2, per: 20)`.
    /// `withTotal: true` also runs a COUNT so the page carries `total`/`totalPages`.
    public func paginate(page: Int, per: Int, withTotal: Bool = false,
                         in db: Database? = nil) async throws -> Page<M> {
        let page = max(1, page)
        let per = max(1, per)
        // Saturate the offset instead of trapping — `page`/`per` come straight from query
        // params, so `(page-1)*per` can overflow (Int is 32-bit on the Wasm guest). An
        // absurd offset just yields an empty page rather than crashing the worker.
        let (product, overflow) = (page - 1).multipliedReportingOverflow(by: per)
        return try await paginate(limit: per, offset: overflow ? Int.max : product, withTotal: withTotal, in: db)
    }

    /// The first matching row, or nil.
    public func first(in db: Database? = nil) async throws -> M? {
        try await limit(1).all(in: db).first
    }

    /// COUNT(*) of matching rows.
    public func count(in db: Database? = nil) async throws -> Int {
        let db = resolvedDatabase(db)
        let predicate = effectivePredicate
        var sql = "SELECT COUNT(*) FROM " + M.schema.table
        if let predicate { sql += " WHERE " + predicate.sql }
        let result = try await db.query(sql, predicate?.bindings ?? [])
        guard let row = result.rows.first else { return 0 }
        return Row(row).int(0)
    }
}

// MARK: - Model query entry points

extension Model {
    /// All rows: `Post.all().order(by:).all(in:)` or just `Post.all().all(in:)`.
    public static func all() -> Query<Self> { Query<Self>() }

    /// Start a filtered query: `Post.where(Post.views > 100)`.
    public static func `where`(_ p: Predicate<Self>) -> Query<Self> {
        Query<Self>().where(p)
    }
}

/// Render an Int as an ASCII decimal literal (LIMIT is a structural literal, not a
/// bound value). Avoids any Unicode-aware String formatting.
func integerLiteral(_ value: Int) -> String {
    String(value)
}

extension Response {
    /// Serialize a `Page` of resources with its pagination metadata:
    /// `{"items": […], "limit": …, "offset": …, "hasMore": …}` — the shape
    /// `paginatedJSON` defines, so hand-rolled and ORM-paginated endpoints match.
    public static func json<M: Model & JSONRepresentable>(_ page: Page<M>, status: Int = 200) -> Response {
        var envelope = paginatedJSON(page.items.map(\.jsonValue), limit: page.limit,
                                     offset: page.offset, hasMore: page.hasMore)
        if case .object(var pairs) = envelope, let total = page.total {
            pairs.append((name: "total", value: .int(Int64(total))))
            pairs.append((name: "page", value: .int(Int64(page.page))))
            envelope = .object(pairs)
        }
        return .json(envelope, status: status)
    }
}
